"""empty message

Revision ID: 932a8a5e56df
Revises: e2b1cbef768d
Create Date: 2020-08-25 22:02:49.380274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932a8a5e56df'
down_revision = 'e2b1cbef768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(), nullable=True))
    op.execute("UPDATE venue SET seeking_description = 'a description' WHERE venue.seeking_description IS NULL;")
    op.execute("UPDATE venue SET seeking_talent = True WHERE venue.seeking_talent IS NULL;")
    op.execute("UPDATE venue SET website = 'www.w.com' WHERE venue.website IS NULL;")
    op.alter_column('venue', 'seeking_description', nullable=False)
    op.alter_column('venue', 'seeking_talent', nullable=False)
    op.alter_column('venue', 'website', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'seeking_description')
    # ### end Alembic commands ###
