"""empty message

Revision ID: af443cfa1733
Revises: 0d7ed65de5bb
Create Date: 2020-08-25 21:40:29.499317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af443cfa1733'
down_revision = '0d7ed65de5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE venue SET genres = ARRAY['Hip Hop'] WHERE genres IS NULL;")
    op.alter_column('venue', 'genres', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
