"""empty message

Revision ID: 3966764ac5bd
Revises: 8938cfaeed68
Create Date: 2020-08-19 00:20:10.315778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3966764ac5bd'
down_revision = '8938cfaeed68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. we allow null values for column 'completed'
    op.add_column('todo', sa.Column('completed', sa.Boolean(), default=False, nullable=True))
    # ### end Alembic commands ###

    # 2. update the existing records to make values for 'completed' as 'false'
    op.execute("UPDATE todo SET completed = False WHERE completed IS NULL;")

    # 3. change nullable=False back to column 'completed'
    op.alter_column('todo', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
